import './globals.css'; 
import Header from "./components/header/header.js"
import "@fortawesome/fontawesome-svg-core/styles.css";
import { config } from "@fortawesome/fontawesome-svg-core";
config.autoAddCss = false;


import { Inter,Poppins } from 'next/font/google'
const inter = Poppins({ subsets: ['latin'],weight: ['100','200','300','400','500','600','700','800','900'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header/>
        {children}
      </body>
    </html>
  )
}
